DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user(
	user_id INTEGER PRIMARY KEY,
	user_name VARCHAR(100) UNIQUE NOT NULL,
	user_token VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE post(
	post_id INTEGER PRIMARY KEY,
	post_user_id INTEGER NOT NULL,
	post_body TEXT NOT NULL,
	FOREIGN KEY (post_user_id) REFERENCES user (user_id)
);

